apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: oauth2-proxy
  namespace: auth
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: gcp-secret-manager
  target:
    name: oauth2-proxy
    creationPolicy: Owner
  data:
    - secretKey: client-secret
      remoteRef:
        key: oidc-client-secret
    - secretKey: cookie-secret
      remoteRef:
        key: oauth2-proxy-cookie-secret
