apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: octomatron-github
  namespace: octomatron
  labels:
    app.kubernetes.io/name: octomatron
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: gcp-secret-manager
  target:
    name: octomatron-github
    creationPolicy: Owner
  data:
    - secretKey: app-id
      remoteRef:
        key: octomatron-github-app-id
    - secretKey: private-key
      remoteRef:
        key: octomatron-github-private-key
    - secretKey: webhook-secret
      remoteRef:
        key: octomatron-github-webhook-secret
