apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: docs
  namespace: docs
  labels:
    app.kubernetes.io/name: docs
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: docs
  policyTypes:
    - Ingress
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: traefik
      ports:
        - protocol: TCP
          port: 8080
