apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: auth
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "4"
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: auth
  sources:
    - repoURL: https://oauth2-proxy.github.io/manifests
      chart: oauth2-proxy
      targetRevision: 10.7.0
      helm:
        releaseName: oauth2-proxy
        valueFiles:
          - $values/platform/auth/values.yaml
    - repoURL: https://github.com/arikkfir-org/delivery
      targetRevision: main
      ref: values
    - repoURL: https://github.com/arikkfir-org/delivery
      targetRevision: main
      path: platform/auth/manifests
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    managedNamespaceMetadata:
      labels:
        kfirs.com/public-ingress: "true"
    retry:
      limit: 10
      refresh: true
      backoff:
        duration: 10s
        factor: 2
        maxDuration: 5m
    syncOptions:
      - CreateNamespace=true
      - SkipDryRunOnMissingResource=true
