apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nats
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: nats
  sources:
    - repoURL: https://nats-io.github.io/k8s/helm/charts
      chart: nats
      targetRevision: 2.15.0
      helm:
        releaseName: nats
        valueFiles:
          - $values/platform/nats/values.yaml
    - repoURL: https://github.com/arikkfir-org/delivery
      targetRevision: main
      ref: values
    - repoURL: https://github.com/arikkfir-org/delivery
      targetRevision: main
      path: platform/nats/manifests
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    retry:
      limit: 10
      refresh: true
      backoff:
        duration: 10s
        factor: 2
        maxDuration: 5m
    syncOptions:
      - CreateNamespace=true
