apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: octomaton
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "4"
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: octomaton
  source:
    repoURL: https://github.com/arikkfir-org/delivery
    targetRevision: main
    path: platform/octomaton/manifests
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    managedNamespaceMetadata:
      labels:
        kfirs.com/public-ingress: "true"
    retry:
      limit: 10
      refresh: true
      backoff:
        duration: 10s
        factor: 2
        maxDuration: 5m
    syncOptions:
      - CreateNamespace=true
      - SkipDryRunOnMissingResource=true
