apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: traefik
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: traefik
  sources:
    - repoURL: https://traefik.github.io/charts
      chart: traefik
      targetRevision: 41.6.0
      helm:
        releaseName: traefik
        valueFiles:
          - $values/platform/traefik/values.yaml
    - repoURL: https://github.com/arikkfir-org/delivery
      targetRevision: main
      ref: values
    - repoURL: https://github.com/arikkfir-org/delivery
      targetRevision: main
      path: platform/traefik/manifests
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    retry:
      limit: 10
      refresh: true
      backoff:
        duration: 10s
        factor: 2
        maxDuration: 5m
    syncOptions:
      - CreateNamespace=true
      - SkipDryRunOnMissingResource=true
